# Site settings
title: "Shaheer Zeb Portfolio"
description: "Portfolio"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shaheer Zeb Khan"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shaheerzeb1@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+923000920039"
resume_contact_address:         "Timergara, Dir (L), Khyber Pakhtunkhwa, Pakistan"

resume_header_contact_info:     "Timergara, Dir (L), Khyber Pakhtunkhwa, Pakistan • +923000920039 • shaheerzeb1@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>With a solid foundation and three years of experience as a Backend professional, I have distinguished myself by creating scalable and robust applications powered by contemporary frameworks. I enlisted perpetual education as a top priority to stay conversant with the rapidly transforming technological landscape. My aptitude for team collaboration has particularly proven effective when working within cross-functional teams. Having gained exceptional expertise in all components of software development, my specialty lies in ideating and implementing high-impact, innovative solutions that address intricate challenges. Now, I am enthusiastic about the prospect to bring my skills, expertise, and innovative mindset to contribute to your team's exciting journey.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_skills:          true
resume_section_projects:        true
resume_section_education:       true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/shaheer-zeb-khan"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
